config/routes.rb
# == Route Map
#
#                  Prefix Verb   URI Pattern                             Controller#Action
#                   about GET    /about(.:format)                        static_pages#about
#                     lab GET    /lab(.:format)                          static_pages#lab
#                  signup GET    /signup(.:format)                       users#new
#                   login GET    /login(.:format)                        sessions#new
#                         POST   /login(.:format)                        sessions#create
#                  logout DELETE /logout(.:format)                       sessions#destroy
#          following_user GET    /users/:id/following(.:format)          users#following
#          followers_user GET    /users/:id/followers(.:format)          users#followers
#                   users GET    /users(.:format)                        users#index
#                         POST   /users(.:format)                        users#create
#                new_user GET    /users/new(.:format)                    users#new
#               edit_user GET    /users/:id/edit(.:format)               users#edit
#                    user GET    /users/:id(.:format)                    users#show
#                         PATCH  /users/:id(.:format)                    users#update
#                         PUT    /users/:id(.:format)                    users#update
#                         DELETE /users/:id(.:format)                    users#destroy
#           relationships POST   /relationships(.:format)                relationships#create
#            relationship DELETE /relationships/:id(.:format)            relationships#destroy
# edit_account_activation GET    /account_activations/:id/edit(.:format) account_activations#edit
#         password_resets POST   /password_resets(.:format)              password_resets#create
#      new_password_reset GET    /password_resets/new(.:format)          password_resets#new
#     edit_password_reset GET    /password_resets/:id/edit(.:format)     password_resets#edit
#          password_reset PATCH  /password_resets/:id(.:format)          password_resets#update
#                         PUT    /password_resets/:id(.:format)          password_resets#update
#              microposts POST   /microposts(.:format)                   microposts#create
#               micropost DELETE /microposts/:id(.:format)               microposts#destroy
#                         GET    /microposts(.:format)                   static_pages#home
#                contacts GET    /contacts(.:format)                     contacts#new
#                         POST   /contacts(.:format)                     contacts#create
#             new_contact GET    /contacts/new(.:format)                 contacts#new
#                    root GET    /                                       static_pages#home
#

Rails.application.routes.draw do

  get    'about'   => 'static_pages#about'
  get    'lab'     => 'static_pages#lab'
  get    'signup'  => 'users#new'        # show signup form
  get    'login'   => 'sessions#new'     # show login form
  post   'login'   => 'sessions#create'  # create a new session
  delete 'logout'  => 'sessions#destroy' # delete a session

  resources :users do
    # To add following and followers actions to each user.
    member do
      get :following, :followers
    end
  end

  resources :relationships,       only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]

  # To avoid error caused by paginating from Microposts controller.
  get    'microposts' => 'static_pages#home'

  # Contact form
  get       'contacts' => 'contacts#new'
  resources :contacts, only: [:new, :create]

  root 'static_pages#home'
end

app/views/layouts/_bootstrap_screen_size.html.haml
%p.panel.bootstrap_screen_size
  Bootstrap Screen Size
  %span.label.label-info.visible-lg Large
  %span.label.label-info.visible-md Medium
  %span.label.label-info.visible-sm Small
  %span.label.label-info.visible-xs Extra Small
  %span.label.label-info.visible-print Print

app/views/layouts/_flash_message.html.haml
- flash.each do |message_type, message|
  %div{ class:["alert", "alert-#{message_type}"] }
    = message

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    The
    = link_to("Ruby on Rails Tutorial", "http://www.railstutorial.org/")
    by
    = link_to("Michael Hartl", "http://www.michaelhartl.com/")

  %nav
    %ul
      %li= link_to "About", about_path
      %li= link_to "Lab",   lab_path
      %li= link_to "News", "http://news.railstutorial.org/"

app/views/layouts/_header.html.haml
-# To activate dropdown menu,
-# add the Bootstrap JavaScript library to application.js.

%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    .navbar-header
      = link_to "MNishiguchi", root_path, id: 'logo'

      / User name
      - if user_logged_in?
        .navbar-text.label-lg.label-primary.hidden-xs
          Logged in as
          = link_to current_user.name, current_user

      / Hamburger button
      %button{ type: 'button', class: 'navbar-toggle collapsed',
        data: { toggle: 'collapse', target: '#hamburger-navigation' } }
        %span.sr-only Navigation toggle
        - 3.times do
          %span.icon-bar

    / Nav links
    %nav.collapse.navbar-collapse#hamburger-navigation
      %ul{ class: 'nav navbar-nav navbar-right', role: 'menu' }

        %li= link_to "Home", root_path
        %li= link_to "Contact", contacts_path

        -# Show different menu items depending on the login status.
        -if user_logged_in?
          %li= link_to "Users", users_path
          %li.dropdown
            %a{ class: 'dropdown-toggle', role:'button', data: { toggle: 'dropdown'} }
              Account
              %b.caret

            %ul.dropdown-menu
              %li= link_to "Profile", current_user
              %li= link_to "Settings", edit_user_path(current_user)
              %li.divider
              %li= link_to "Log out", logout_path, method: :delete
        -else
          %li= link_to "Log in", login_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  %script{ src: "//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js" }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/

    %title= full_title(yield(:title))

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    = render 'layouts/shim'

  %body
    = render 'layouts/header'

    .container
      = render 'layouts/flash_message'
      = yield  # contents
      = render 'layouts/footer'

      - if Rails.env.development?
        = debug(params)
        = render 'layouts/bootstrap_screen_size'